Web_Practice/Rabbit_Web/Models/Note.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rabbit_Web.Models {
    public class Note 
    {
        /// <summary>
        /// 게시물번호
        /// </summary>
        [Key]
        public int NoteNo { get; set; }
        /// <summary>
        /// 게시물 제목
        /// </summary>
        
        [Required(ErrorMessage ="게시물 제목을 입력하세요.")]
        public string NoteTitle { get; set; }
        /// <summary>
        /// 게시물 내용
        /// </summary>
        [Required(ErrorMessage = "게시물 내용을 입력하세요.")]
        public string NoteContents { get; set; }
        /// <summary>
        /// 작성자 번호
        /// </summary>
        [Required]
        public int UserNo { get; set; } //작성자

        //UserNo를 통해서 UserName을 가지고 오기 위해서(Join과 같은 역할)
        [ForeignKey("UserNo")]  
        public virtual User User { get; set; }
    }
}

Web_Practice/Rabbit_Web/Controllers/NoteController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Rabbit_Web.DataContext;
using Rabbit_Web.Models;
using System.Collections.Generic;
using System.Linq;

namespace Rabbit_Web.Controllers {
    public class NoteController : Controller {
        /// <summary>
        /// 게시판 리스트
        /// </summary>
        /// <returns></returns>
        public IActionResult Index() {
            if (HttpContext.Session.GetInt32("USER_LOGIN_KEY")==null)
            {
                //로그인이 안된 상태
                return RedirectToAction("Login", "Account");
            }
            using (var db = new AspnetNoteDbContext()) 
            {
                var list = db.Notes.ToList();
                return View(list);
            }
        }
        /// <summary>
        /// 게시판 상세
        /// </summary>
        /// <param name="noteNo"></param>
        /// <returns></returns>
        public IActionResult Detail(int noteNo)
        {
            if (HttpContext.Session.GetInt32("USER_LOGIN_KEY") == null)
            {
                //로그인이 안된 상태
                return RedirectToAction("Login", "Account");

            }
            using (var db = new AspnetNoteDbContext() )
            {
                var note = db.Notes.FirstOrDefault(x => x.NoteNo.Equals(noteNo));
                return View(note);
            }
        }
        /// <summary>
        /// 게시물 추가
        /// </summary>
        /// <returns></returns>
        public IActionResult Add() {
            return View();
        }
        [HttpPost]
        public IActionResult Add(Note model)
        {
            if (HttpContext.Session.GetInt32("USER_LOGIN_KEY") == null)
            {
                //로그인이 안된 상태
                return RedirectToAction("Login", "Account");
            }
            model.UserNo = int.Parse(HttpContext.Session.GetInt32("USER_LOGIN_KEY").ToString());

            if (ModelState.IsValid)
            {
                using(var db = new AspnetNoteDbContext())
                {
                    db.Notes.Add(model);
                    if (db.SaveChanges() >0) //Commit이 한개 이상일 경우 True
                    {
                        return Redirect("Index");   //동일한 컨트롤러에서는 Redirect, 다른 컨트롤러의 경우 RedirectToAction
                    }

                }
                ModelState.AddModelError(string.Empty, "게시물을 저장할 수 없습니다.");
            }
            return View(model);
        }

        /// <summary>
        /// 게시물 수정
        /// </summary>
        /// <returns></returns>
        public IActionResult Edit() {
            if (HttpContext.Session.GetInt32("USER_LOGIN_KEY") == null)
            {
                //로그인이 안된 상태
                return RedirectToAction("Login", "Account");
            }

            return View();
        }
        

        /// <summary>
        /// 게시물 삭제
        /// </summary>
        /// <returns></returns>
        public IActionResult Delete() {
            if (HttpContext.Session.GetInt32("USER_LOGIN_KEY") == null)
            {
                //로그인이 안된 상태
                return RedirectToAction("Login", "Account");
            }

            return View();
        }
    }
}

Web_Practice/Rabbit_Web/Views/Note/Add.cshtml
@model Rabbit_Web.Models.Note
<div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-8">
        <form class="form-horizontal" method="post" asp-controller="Note" asp-action="Add">
            <div class="text-danger" asp-validation-summary="ModelOnly"></div> @*AddModelError와 호환됨*@
            <div class=" form-group">
                <label>제목</label>
                <input type="text" class="form-control" asp-for="NoteTitle"  placeholder="제목 입력"/>
                <span class="text-danger" asp-validation-for="NoteTitle"></span>

            </div>
            <div class=" form-group">
                <textarea class="form-control editor" rows="20" asp-for="NoteContents" placeholder="내용 입력"></textarea>
                <span class="text-danger" asp-validation-for="NoteContents"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary"> 저장 </button>
                <a class="btn btn-light" asp-controller="Note" asp-action="Index">취소</a>
            </div>
        </form>
    </div>
    <div class="col-lg-2"></div>
</div>

Web_Practice/Rabbit_Web/Views/Note/Detail.cshtml
@model Rabbit_Web.Models.Note

<div class="row">
    <div class="col-lg-12">
        <h3 class="toast-header">상세 읽기 - @Model.NoteTitle</h3>
    </div>
</div>

<div class="row">
    <div class="col-lg-10">
        <div class="panel panel-default">
            <div class="panel-heading">
                <label>제목 : </label>@Model.NoteTitle
            </div>
            <div class="panel-body">
                @Html.Raw(Model.NoteContents)
            </div>
            <div class="panel-footer">
                <a class="btn btn-primary" asp-controller="Note" asp-action="Index">목록</a>
            </div>
        </div>
    </div>
</div>

Web_Practice/Rabbit_Web/Views/Note/Index.cshtml
@*@model Rabbit_Web.Models.Note*@

<table class="table table-bordered">
    <thead>
        <tr>
            <th>번호</th>
            <th>제목</th>
            <th>작성자</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Note note in Model) {
            <tr>
                <td>@note.NoteNo</td>
                <td>
                    <a asp-controller="Note" asp-action="Detail" asp-route-noteNo="@note.NoteNo">@note.NoteTitle</a>
                    
                </td>
                <td>@note.UserNo</td>
            </tr>
        }
    </tbody>
</table>

<a class="btn btn-warning" asp-controller="Note" asp-action="Add">게시물 작성</a>